# cloudbuild.yaml
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/google-ads-mcp:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/google-ads-mcp:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'google-ads-mcp'
    - '--image'
    - 'gcr.io/$PROJECT_ID/google-ads-mcp:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--no-allow-unauthenticated'
    - '--service-account'
    - '[SERVICE_ACCOUNT_EMAIL]'
    - '--port'
    - '8080'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '10'
    - '--set-env-vars'
    - 'GOOGLE_ADS_AUTH_TYPE=oauth,GOOGLE_ADS_DEVELOPER_TOKEN=[DEVELOPER_TOKEN],GOOGLE_ADS_LOGIN_CUSTOMER_ID=[CUSTOMER_ID]'

images:
  - 'gcr.io/$PROJECT_ID/google-ads-mcp:$COMMIT_SHA'